@org = axgonz
@repo = azure-nextflow-cipa
@branch = main
@project = cipa
@az_funcName = fcnj6h

GET https://{{az_funcName}}.azurewebsites.net/api/nxfutil HTTP/1.1

### bepridil

POST https://{{az_funcName}}.azurewebsites.net/api/nxfutil HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/pipeline.nf",
    "parameters_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/bepridil.json",
    "auto_delete": true
}

### chlorpromazine

POST https://{{az_funcName}}.azurewebsites.net/api/nxfutil HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/pipeline.nf",
    "parameters_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/chlorpromazine.json",
    "auto_delete": true
}